locale: "en-US"
site_theme: "default"
title: "Jiarui Han's Personal Page"
title_separator: "-"
name: "Jiarui Han"
description: "Personal website of Jiarui Han"
url: "https://billhan01.github.io"
baseurl: ""
repository: "BillHan01/BillHan01.github.io"

author:
  avatar: "hanjiarui.png"
  name: "Jiarui Han"
  bio: "Master's Student in Computer Science"
  location: "Shanghai, P.R. China"
  employer: "Tongji University"
  email: "tjbillhan@gmail.com"
  github: "BillHan01"
  huggingface: "Billhan01"
  instagram: "billhan1228"
  linkedin: "jiarui-han-915294242"

breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"

atom_feed:
  hide: false

analytics:
  provider: false

include:
  - _pages
exclude:
  - .bundle
  - .devcontainer
  - .github
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - Dockerfile
  - Gemfile
  - LICENSE
  - node_modules
  - package.json
  - README.md
  - vendor

encoding: "utf-8"
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Shanghai

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
